name: ğŸš€ Pull Request

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  pull_request:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  eslint:
    name: â¬£ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¥ Download deps with pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: ğŸ”¬ Lint
        run: pnpm run lint

  commitlint:
    name: âš™ï¸ CommitLint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: âš™ï¸ Commitlint
        uses: wagoid/commitlint-github-action@v6

  knip:
    name: ğŸ“¦ Knip
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¥ Download deps with pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: ğŸ“¦ Knip
        run: pnpm run knip

  deploy:
    name: ğŸš€ Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¥ Download deps with pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: ğŸ“¦ Install Vercel CLI
        run: npm install --global vercel@latest

      - name: ğŸ”„ Pull Vercel Environment Variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --git-branch=${{ github.head_ref }}

      - name: ğŸ—ï¸ Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Deploy Project to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

      - name: ğŸ“ Comment PR with Preview URL
        run: |
          URL=$(cat deployment-url.txt)
          echo "Vercel preview URL: $URL"
          gh pr comment ${{ github.event.pull_request.number }} --body "Vercel preview URL: $URL"